library(Seurat)
library(cowplot)
library(hdf5r)
library(kableExtra)
library(biomaRt)
library(limma)
library(topGO)
library(org.Hs.eg.db)
library(sva)
library(scran)
library(tidyverse)
library(DoubletFinder)
library(gprofiler2)
library(rliger)
library(future)
library(harmony)
library(pheatmap)
library(clustree)
library(venn)
library(enrichR)
library(rafalib)
library(scPred)
library(loomR)
library(SeuratWrappers)
library(velocyto.R)
library("Nebulosa")
library(ggalluvial)
library(patchwork)
plan("multicore", workers = 10)
options(future.globals.maxSize = 28 * 1024 ^ 3)
set.seed(12345)

alldataF <- readRDS("Main_seuratObject.rds")

library(janitor)

WT <- table(paste0(alldataF@meta.data$RNA_snn_res.0.5, alldataF@meta.data$`CEBPa-WT`))
IS10 <- table(paste0(alldataF@meta.data$RNA_snn_res.0.5, alldataF@meta.data$`CEBPa-AroPERFECT-IS10`))
IS15 <- table(paste0(alldataF@meta.data$RNA_snn_res.0.5, alldataF@meta.data$`CEBPa-AroPERFECT-IS15`))
Mkp2 <- rbind(WT,IS10,IS15)
Mkp2 <- as.data.frame(Mkp2)
meta.data <- alldataF[[]]
countsWT <- group_by(meta.data, `CEBPa-WT`, RNA_snn_res.0.5) %>% summarise(count = n())

countsall <- group_by(meta.data, type, RNA_snn_res.0.5) %>% summarise(count = n())

geobcols <- c("#ef4448", "#d57128", "#3e2d80")
ggplot(countsall, aes(RNA_snn_res.0.5, count, fill = type)) +
  geom_bar(position="fill", stat = 'identity') +
  labs(fill = "") + theme_bw() + scale_fill_manual(values = geobcols)