library(Seurat)
library(cowplot)
library(hdf5r)
library(kableExtra)
library(biomaRt)
library(limma)
library(topGO)
library(org.Hs.eg.db)
library(sva)
library(scran)
library(tidyverse)
library(DoubletFinder)
library(gprofiler2)
library(rliger)
library(future)
library(harmony)
library(pheatmap)
library(clustree)
library(venn)
library(enrichR)
library(rafalib)
library(scPred)
library(loomR)
library(SeuratWrappers)
library(velocyto.R)
library("Nebulosa")
library(ggalluvial)
library(patchwork)
plan("multicore", workers = 10)
options(future.globals.maxSize = 28 * 1024 ^ 3)
set.seed(12345)

alldataF <- readRDS("Main_seuratObject.rds")

library(janitor)
#Markergene <- c("meGFP", "CEBPa-WT", "CEBPa-AroPERFECT-IS10", "CEBPa-AroPERFECT-IS15")

meGFP <- table(paste0(alldataF@meta.data$RNA_snn_res.0.5, alldata@meta.data$meGFP))
Mkp <- rbind(meGFP)
Mkp <- as.data.frame(Mkp)
meta.data <- alldataF[[]]
counts <- group_by(meta.data, meGFP, RNA_snn_res.0.5) %>% summarise(count = n())

write.csv(counts, "Cells_meGFP_PosNeg_perCluster.csv")
ggplot(counts, aes(RNA_snn_res.0.5, count, fill = meGFP)) +
  geom_bar(position="fill", stat = 'identity') + theme_bw() + scale_fill_manual(values = c("#3b518b","#5cc763"))