library(GenomicRanges)
library(SummarizedExperiment)
library(JASPAR2022)
library(TFBSTools)
library(BSgenome.Hsapiens.UCSC.hg38)
library(monaLisa)
library(ComplexHeatmap)
library(circlize)

CEBPa_WT_IS15_Common <- rtracklayer::import(con = "CEBPa_WT_IS15_Common.bed", format = "bed")
IS15_unique <- rtracklayer::import(con = "CEBPa_IS15_unique_filtered_dectedtedBefore_wa.bed", format = "bed")
IS15_specific <- rtracklayer::import(con = "CEBPa_IS15_unique_filtered_neverDetected_FilteredCEBPa_F.bed", format = "bed")

pwms <- getMatrixSet(JASPAR2022,
                     opts = list(matrixtype = "PWM",
                                 tax_group = "vertebrates"))

MergedSet <- c(CEBPa_WT_IS15_Common, IS15_unique, IS15_specific)

# get TFBS on given GRanges (peaks)
# suppress warnings generated by matchPWM due to the presence of Ns 
# in the sequences
peakMerged <- getSeq(BSgenome.Hsapiens.UCSC.hg38, MergedSet)

# define binning vector
bins <- rep(c("CEBPa_WT_IS15_Common", "IS15_unique", "IS15_specific"), c(length(CEBPa_WT_IS15_Common), length(IS15_unique), length(IS15_specific)))
bins <- factor(bins)
table(bins)


se <- calcBinnedMotifEnrR(seqs = peakMerged, bins = bins,
                          background = "genome",
                          genome = BSgenome.Hsapiens.UCSC.hg38,
                          genome.regions = NULL, # sample from full genome
                          genome.oversample = 2,
                          BPPARAM = BiocParallel::SerialParam(RNGseed = 42),
                          pwmL = pwms)
se

se2 <- calcBinnedMotifEnrR(seqs = peakMerged, bins = bins,
                           background = "allBins",
                           genome = BSgenome.Hsapiens.UCSC.hg38,
                           genome.regions = NULL, # sample from full genome
                           genome.oversample = 2,
                           BPPARAM = BiocParallel::SerialParam(RNGseed = 42),
                           pwmL = pwms)
se2

se3 <- calcBinnedMotifEnrR(seqs = peakMerged, bins = bins,
                           background = "otherBins",
                           genome = BSgenome.Hsapiens.UCSC.hg38,
                           genome.regions = NULL, # sample from full genome
                           genome.oversample = 2,
                           BPPARAM = BiocParallel::SerialParam(RNGseed = 42),
                           pwmL = pwms)
se3

SimMatSel <- motifSimilarity(rowData(se)$motif.pfm)
hcl <- hclust(as.dist(1 - SimMatSel), method = "average")

# plot
plotMotifHeatmaps(x = se, which.plots = c("log2enr", "negLog10Padj"), 
                  width = 1.0, cluster = hcl,  maxEnr = 4, maxSig = 20, 
                  show_motif_GC = F, show_seqlogo = T,show_dendrogram = TRUE, doPlot = T)

plotMotifHeatmaps(x = se2, which.plots = c("log2enr", "negLog10Padj"), 
                  width = 1.0, cluster = hcl,  maxEnr = 4, maxSig = 20, 
                  show_motif_GC = F, show_seqlogo = T,show_dendrogram = TRUE, doPlot = T)

plotMotifHeatmaps(x = se3, which.plots = c("log2enr", "negLog10Padj"), 
                  width = 1.0, cluster = hcl,  maxEnr = 4, maxSig = 20, 
                  show_motif_GC = F, show_seqlogo = T,show_dendrogram = TRUE, doPlot = T)